# SITE CONFIGURATION
baseurl: "/blog"
url: "https://ayushagarwal.ml/blog/"
title: Ayush Agarwal's blog # site's title
description: "Personal blog of Ayush Agarwal" # used by search engines


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "Ayush Agarwal" # blog's title
  avatar: assets/img/mylogo.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash

  # Header and footer text
  header_text: > #two or three lines to describe your site
    <p></p><br><br><br><br>     
  header_text_feature_image: assets/img/pexels/computer.jpeg
  footer_text: >
   Personal Blog of <a href = "https://ayushagarwal.ml/blog/about/">Ayush Agarwal</a>

  # Icons
  rss: true  # Make sure you created a feed.xml with feed.xml layout
  email_address: "aagarwal9782@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "aagarwal1012"
  flickr:
  gitlab:
  github: "aagarwal1012"
  google_plus: 115147319139238316033
  instagram: "superman_ayush"
  keybase:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "aagarwal9782"
  vimeo:
  wordpress:
  youtube: "UCQsnIvnC7zeOhSImDOJmESA"
  
  # Sharing options
  share_buttons:
    facebook: true
    twitter: true
    google_plus: true
    tumblr:
    pinterest:
    pocket:
    reddit: 
    linkedin:
    wordpress:
    email: true

  # Scripts / Features 
  google_analytics: "UA-117131653-1"
  disqus_shortname: true
  katex: true # Enable if using math markup
  
  special_page:
    search: 
      icon: "search" # Assuming page link and icon are the same
      enabled: true
    tags:
      icon: "tags"
      enabled: true
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_share_on: "Share on"
  str_add_to: "Add to"
  str_email: "Email"
  str_tweet: "Tweet"
  str_pin_it: "Pin it"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true
  
  
# PAGINATION
paginate: 5
paginate_path: "blog/page:num"


# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name


# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate, jekyll-seo-tag]
#theme: type-on-strap # Uncomment if using the theme as a jekyll theme gem
exclude: ["Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", "LICENSE", "README.md", "screenshot.png", "package.json", "node_modules", "gulpfile.js", ".idea/*"]
